### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by theshyyi** [thieu1995/cec2011-real-world#1]
### Description of the bug

Hello, I'm sorry to say that I've encountered a lot of problems that are simple for you because I've been testing optimisation algorithms lately.
The problem I have with CEC2011RW is the NotImplementedError, I have checked some information but I don't know a proper solution, I hope you can give me the answer again.I appreciate your support.
![image](https://github.com/thieu1995/cec2011-real-world/assets/59169927/5564f92c-5533-4aef-82cf-ff91211f5e4d)
![image](https://github.com/thieu1995/cec2011-real-world/assets/59169927/4439c451-b447-4203-b3c1-feb0f15b678d)

### Steps To Reproduce

The problem I have with CEC2011RW is the NotImplementedError

**Comment by thieu1995** [comment]
For this specific repository. You need to use the specific version of mealpy 2.5.0 as described in Readme file.
`pip install mealpy==2.5.0`

**Comment by theshyyi** [comment]
Thank you for your reply.This means that with a higher version of mealpy, it is not possible to fix these by modifying the code? You must use mealpy == 2.5.0.

**Comment by thieu1995** [comment]
@theshyyi ,

I have updated with the latest version of mealpy 3.0.1. So you can now using it to solve these cec problems. Make sure you have the correct version of `oct2py=5.6.0` and installed version of `octave=8.4.0`

**Comment by theshyyi** [comment]
This is incredibly exciting news for me, thank you so much!
